sudo: false

services:
  - docker

script:
 - set -e
 - echo 'Build and check docker image'
 - docker build -t nf-qc-module .
 - docker images | grep -c nf-qc-module
 - echo 'Verify program(s) used by this repo'
 - docker run -t --rm nf-sge fastqc --help
 - docker run -t --rm nf-sge multiqc --help
